### ISSUE TITLE
Skill Issue

### ISSUE THREAD

**Issue by ZainKergaye** [cshmookler/archlinux-setup#1]
01000001 01110010 01100011 01101000 00100000 01101001 01110011 00100000 01100110 01101111 01110010 00100000 01101110 01100101 01110010 01100100 01110011 00101100 00100000 01101010 01110101 01110011 01110100 00100000 01110101 01110011 01100101 00100000 01100001 00100000 01100010 01110101 01110100 01110100 01101111 01101110 00100000 01110100 01101111 00100000 01110000 01110101 01110011 01101000 00100000 01110100 01101000 01100101 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01101001 01101110 01110100 01101111 00100000 01110100 01101000 01100101 00100000 01100011 01110000 01110101 00100000 01110010 01100101 01100111 01101001 01110011 01110100 01100101 01110010

**Comment by cshmookler** [comment]
"Arch is for nerds, just use a button to push the binary into the cpu register"

Why even use a computer at all? Just design a circuit that emulates a web browser and you're good.
